const characterAssets = {
  "Albedo" :{
    'gacha_card': require('../assets/CharacterAssets/Albedo/albedo_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Albedo/albedo_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Albedo/albedo_face.png'),
    'c1': require('../assets/CharacterAssets/Albedo/Albedo_C1.png'),
    'c2': require('../assets/CharacterAssets/Albedo/Albedo_C2.png'),
    'c3': require('../assets/CharacterAssets/Albedo/Albedo_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Albedo/Albedo_C4.png'),
    'c5': require('../assets/CharacterAssets/Albedo/Albedo_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Albedo/Albedo_C6.png'),
  },
  "Aloy" :{
    'gacha_card': require('../assets/CharacterAssets/Aloy/aloy_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Aloy/aloy_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Aloy/aloy_face.png'),
    'c1': require('../assets/CharacterAssets/Aloy/Aloy_C1.png'),
    'c2': require('../assets/CharacterAssets/Aloy/Aloy_C1.png'),
    'c3': require('../assets/CharacterAssets/Aloy/Aloy_C1.png'),
    'c4': require('../assets/CharacterAssets/Aloy/Aloy_C1.png'),
    'c5': require('../assets/CharacterAssets/Aloy/Aloy_C1.png'),
    'c6': require('../assets/CharacterAssets/Aloy/Aloy_C1.png'),
  },
  "Amber" :{
    'gacha_card': require('../assets/CharacterAssets/Amber/amber_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Amber/amber_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Amber/amber_face.png'),
    'c1': require('../assets/CharacterAssets/Amber/Amber_C1.png'),
    'c2': require('../assets/CharacterAssets/Amber/Amber_C2.png'),
    'c3': require('../assets/CharacterAssets/Amber/Amber_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Amber/Amber_C4.png'),
    'c5': require('../assets/CharacterAssets/Amber/Amber_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Amber/Amber_C6.png'),
  },
  "Arataki Itto" :{
    'gacha_card': require('../assets/CharacterAssets/Arataki Itto/itto_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Arataki Itto/itto_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Arataki Itto/itto_face.png'),
    'c1': require('../assets/CharacterAssets/Arataki Itto/Itto_C1.png'),
    'c2': require('../assets/CharacterAssets/Arataki Itto/Itto_C2.png'),
    'c3': require('../assets/CharacterAssets/Arataki Itto/Itto_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Arataki Itto/Itto_C4.png'),
    'c5': require('../assets/CharacterAssets/Arataki Itto/Itto_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Arataki Itto/Itto_C6.png'),
  },
  "Barbara" :{
    'gacha_card': require('../assets/CharacterAssets/Barbara/barbara_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Barbara/barbara_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Barbara/barbara_face.png'),
    'c1': require('../assets/CharacterAssets/Barbara/Barb_C1.png'),
    'c2': require('../assets/CharacterAssets/Barbara/Barb_C2.png'),
    'c3': require('../assets/CharacterAssets/Barbara/Barb_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Barbara/Barb_C4.png'),
    'c5': require('../assets/CharacterAssets/Barbara/Barb_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Barbara/Barb_C6.png'),
  },
  "Beidou" :{
    'gacha_card': require('../assets/CharacterAssets/Beidou/beidou_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Beidou/beidou_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Beidou/beidou_face.png'),
    'c1': require('../assets/CharacterAssets/Beidou/Beidou_C1.png'),
    'c2': require('../assets/CharacterAssets/Beidou/Beidou_C2.png'),
    'c3': require('../assets/CharacterAssets/Beidou/Beidou_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Beidou/Beidou_C4.png'),
    'c5': require('../assets/CharacterAssets/Beidou/Beidou_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Beidou/Beidou_C6.png'),
  },
  "Bennett" :{
    'gacha_card': require('../assets/CharacterAssets/Bennett/bennett_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Bennett/bennett_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Bennett/bennett_face.png'),
    'c1': require('../assets/CharacterAssets/Bennett/Bennett_C1.png'),
    'c2': require('../assets/CharacterAssets/Bennett/Bennett_C2.png'),
    'c3': require('../assets/CharacterAssets/Bennett/Bennett_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Bennett/Bennett_C4.png'),
    'c5': require('../assets/CharacterAssets/Bennett/Bennett_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Bennett/Bennett_C6.png'),
  },
  "Chongyun" :{
    'gacha_card': require('../assets/CharacterAssets/Chongyun/chongyun_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Chongyun/chongyun_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Chongyun/chongyun_face.png'),
    'c1': require('../assets/CharacterAssets/Chongyun/Chongyun_C1.png'),
    'c2': require('../assets/CharacterAssets/Chongyun/Chongyun_C2.png'),
    'c3': require('../assets/CharacterAssets/Chongyun/Chongyun_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Chongyun/Chongyun_C4.png'),
    'c5': require('../assets/CharacterAssets/Chongyun/Chongyun_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Chongyun/Chongyun_C6.png'),
  },
  "Diluc" :{
    'gacha_card': require('../assets/CharacterAssets/Diluc/diluc_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Diluc/diluc_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Diluc/diluc_face.png'),
    'c1': require('../assets/CharacterAssets/Diluc/Diluc_C1.png'),
    'c2': require('../assets/CharacterAssets/Diluc/Diluc_C2.png'),
    'c3': require('../assets/CharacterAssets/Diluc/Diluc_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Diluc/Diluc_C4.png'),
    'c5': require('../assets/CharacterAssets/Diluc/Diluc_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Diluc/Diluc_C6.png'),
  },
  "Diona" :{
    'gacha_card': require('../assets/CharacterAssets/Diona/diona_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Diona/diona_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Diona/diona_face.png'),
    'c1': require('../assets/CharacterAssets/Diona/Diona_C1.png'),
    'c2': require('../assets/CharacterAssets/Diona/Diona_C2.png'),
    'c3': require('../assets/CharacterAssets/Diona/Diona_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Diona/Diona_C4.png'),
    'c5': require('../assets/CharacterAssets/Diona/Diona_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Diona/Diona_C6.png'),
  },
  "Eula" :{
    'gacha_card': require('../assets/CharacterAssets/Eula/eula_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Eula/eula_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Eula/eula_face.png'),
    'c1': require('../assets/CharacterAssets/Eula/Eula_C1.png'),
    'c2': require('../assets/CharacterAssets/Eula/Eula_C2.png'),
    'c3': require('../assets/CharacterAssets/Eula/Eula_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Eula/Eula_C4.png'),
    'c5': require('../assets/CharacterAssets/Eula/Eula_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Eula/Eula_C6.png'),
  },
  "Fischl" :{
    'gacha_card': require('../assets/CharacterAssets/Fischl/fischl_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Fischl/fischl_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Fischl/fischl_face.png'),
    'c1': require('../assets/CharacterAssets/Fischl/Fischl_C1.png'),
    'c2': require('../assets/CharacterAssets/Fischl/Fischl_C2.png'),
    'c3': require('../assets/CharacterAssets/Fischl/Fischl_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Fischl/Fischl_C4.png'),
    'c5': require('../assets/CharacterAssets/Fischl/Fischl_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Fischl/Fischl_C6.png'),
  },
  "Ganyu" :{
    'gacha_card': require('../assets/CharacterAssets/Ganyu/ganyu_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Ganyu/ganyu_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Ganyu/ganyu_face.png'),
    'c1': require('../assets/CharacterAssets/Ganyu/Ganyu_C1.png'),
    'c2': require('../assets/CharacterAssets/Ganyu/Ganyu_C2.png'),
    'c3': require('../assets/CharacterAssets/Ganyu/Ganyu_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Ganyu/Ganyu_C4.png'),
    'c5': require('../assets/CharacterAssets/Ganyu/Ganyu_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Ganyu/Ganyu_C6.png'),
  },
  "Gorou" :{
    'gacha_card': require('../assets/CharacterAssets/Gorou/gorou_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Gorou/gorou_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Gorou/gorou_face.png'),
    'c1': require('../assets/CharacterAssets/Gorou/Gorou_C1.png'),
    'c2': require('../assets/CharacterAssets/Gorou/Gorou_C2.png'),
    'c3': require('../assets/CharacterAssets/Gorou/Gorou_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Gorou/Gorou_C4.png'),
    'c5': require('../assets/CharacterAssets/Gorou/Gorou_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Gorou/Gorou_C6.png'),
  },
  "Hu Tao" :{
    'gacha_card': require('../assets/CharacterAssets/Hu Tao/hutao_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Hu Tao/hutao_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Hu Tao/hutao_face.png'),
    'c1': require('../assets/CharacterAssets/Hu Tao/HuTao_C1.png'),
    'c2': require('../assets/CharacterAssets/Hu Tao/HuTao_C2.png'),
    'c3': require('../assets/CharacterAssets/Hu Tao/HuTao_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Hu Tao/HuTao_C4.png'),
    'c5': require('../assets/CharacterAssets/Hu Tao/HuTao_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Hu Tao/HuTao_C6.png'),
  },
  "Jean" :{
    'gacha_card': require('../assets/CharacterAssets/Jean/jean_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Jean/jean_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Jean/jean_face.png'),
    'c1': require('../assets/CharacterAssets/Jean/Jean_C1.png'),
    'c2': require('../assets/CharacterAssets/Jean/Jean_C2.png'),
    'c3': require('../assets/CharacterAssets/Jean/Jean_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Jean/Jean_C4.png'),
    'c5': require('../assets/CharacterAssets/Jean/Jean_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Jean/Jean_C6.png'),
  },
  "Kaedehara Kazuha" :{
    'gacha_card': require('../assets/CharacterAssets/Kaedehara Kazuha/kazuha_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Kaedehara Kazuha/kazuha_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Kaedehara Kazuha/kazuha_face.png'),
    'c1': require('../assets/CharacterAssets/Kaedehara Kazuha/Kazuha_C1.png'),
    'c2': require('../assets/CharacterAssets/Kaedehara Kazuha/Kazuha_C2.png'),
    'c3': require('../assets/CharacterAssets/Kaedehara Kazuha/Kazuha_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Kaedehara Kazuha/Kazuha_C4.png'),
    'c5': require('../assets/CharacterAssets/Kaedehara Kazuha/Kazuha_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Kaedehara Kazuha/Kazuha_C6.png'),
  },
  "Kaeya" :{
    'gacha_card': require('../assets/CharacterAssets/Kaeya/kaeya_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Kaeya/kaeya_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Kaeya/kaeya_face.png'),
    'c1': require('../assets/CharacterAssets/Kaeya/Kaeya_C1.png'),
    'c2': require('../assets/CharacterAssets/Kaeya/Kaeya_C2.png'),
    'c3': require('../assets/CharacterAssets/Kaeya/Kaeya_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Kaeya/Kaeya_C4.png'),
    'c5': require('../assets/CharacterAssets/Kaeya/Kaeya_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Kaeya/Kaeya_C6.png'),
  },
  "Kamisato Ayaka" :{
    'gacha_card': require('../assets/CharacterAssets/Kamisato Ayaka/ayaka_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Kamisato Ayaka/ayaka_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Kamisato Ayaka/ayaka_face.png'),
    'c1': require('../assets/CharacterAssets/Kamisato Ayaka/Ayaka_C1.png'),
    'c2': require('../assets/CharacterAssets/Kamisato Ayaka/Ayaka_C2.png'),
    'c3': require('../assets/CharacterAssets/Kamisato Ayaka/Ayaka_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Kamisato Ayaka/Ayaka_C4.png'),
    'c5': require('../assets/CharacterAssets/Kamisato Ayaka/Ayaka_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Kamisato Ayaka/Ayaka_C6.png'),
  },
  "Kamisato Ayato" :{
    'gacha_card': require('../assets/CharacterAssets/Kamisato Ayato/ayato_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Kamisato Ayato/ayato_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Kamisato Ayato/ayato_face.png'),
    'c1': require('../assets/CharacterAssets/Kamisato Ayato/Ayato_C1.png'),
    'c2': require('../assets/CharacterAssets/Kamisato Ayato/Ayato_C2.png'),
    'c3': require('../assets/CharacterAssets/Kamisato Ayato/Ayato_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Kamisato Ayato/Ayato_C4.png'),
    'c5': require('../assets/CharacterAssets/Kamisato Ayato/Ayato_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Kamisato Ayato/Ayato_C6.png'),
  },
  "Keqing" :{
    'gacha_card': require('../assets/CharacterAssets/Keqing/keqing_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Keqing/keqing_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Keqing/keqing_face.png'),
    'c1': require('../assets/CharacterAssets/Keqing/Keqing_C1.png'),
    'c2': require('../assets/CharacterAssets/Keqing/Keqing_C2.png'),
    'c3': require('../assets/CharacterAssets/Keqing/Keqing_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Keqing/Keqing_C4.png'),
    'c5': require('../assets/CharacterAssets/Keqing/Keqing_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Keqing/Keqing_C6.png'),
  },
  "Klee" :{
    'gacha_card': require('../assets/CharacterAssets/Klee/klee_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Klee/klee_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Klee/klee_face.png'),
    'c1': require('../assets/CharacterAssets/Klee/Klee_C1.png'),
    'c2': require('../assets/CharacterAssets/Klee/Klee_C2.png'),
    'c3': require('../assets/CharacterAssets/Klee/Klee_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Klee/Klee_C4.png'),
    'c5': require('../assets/CharacterAssets/Klee/Klee_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Klee/Klee_C6.png'),
  },
  "Kujou Sara" :{
    'gacha_card': require('../assets/CharacterAssets/Kujou Sara/sara_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Kujou Sara/sara_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Kujou Sara/sara_face.png'),
    'c1': require('../assets/CharacterAssets/Kujou Sara/Sara_C1.png'),
    'c2': require('../assets/CharacterAssets/Kujou Sara/Sara_C2.png'),
    'c3': require('../assets/CharacterAssets/Kujou Sara/Sara_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Kujou Sara/Sara_C4.png'),
    'c5': require('../assets/CharacterAssets/Kujou Sara/Sara_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Kujou Sara/Sara_C6.png'),
  },
  "Kuki Shinobu" :{
    'gacha_card': require('../assets/CharacterAssets/Kuki Shinobu/shinobu_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Kuki Shinobu/shinobu_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Kuki Shinobu/shinobu_face.png'),
    'c1': require('../assets/CharacterAssets/Kuki Shinobu/Kuki_C1.png'),
    'c2': require('../assets/CharacterAssets/Kuki Shinobu/Kuki_C2.png'),
    'c3': require('../assets/CharacterAssets/Kuki Shinobu/Kuki_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Kuki Shinobu/Kuki_C4.png'),
    'c5': require('../assets/CharacterAssets/Kuki Shinobu/Kuki_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Kuki Shinobu/Kuki_C6.png'),
  },
  "Lisa" :{
    'gacha_card': require('../assets/CharacterAssets/Lisa/lisa_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Lisa/lisa_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Lisa/lisa_face.png'),
    'c1': require('../assets/CharacterAssets/Lisa/Lisa_C1.png'),
    'c2': require('../assets/CharacterAssets/Lisa/Lisa_C2.png'),
    'c3': require('../assets/CharacterAssets/Lisa/Lisa_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Lisa/Lisa_C4.png'),
    'c5': require('../assets/CharacterAssets/Lisa/Lisa_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Lisa/Lisa_C6.png'),
  },
  "Mona" :{
    'gacha_card': require('../assets/CharacterAssets/Mona/mona_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Mona/mona_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Mona/mona_face.png'),
    'c1': require('../assets/CharacterAssets/Mona/Mona_C1.png'),
    'c2': require('../assets/CharacterAssets/Mona/Mona_C2.png'),
    'c3': require('../assets/CharacterAssets/Mona/Mona_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Mona/Mona_C4.png'),
    'c5': require('../assets/CharacterAssets/Mona/Mona_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Mona/Mona_C6.png'),
  },
  "Ningguang" :{
    'gacha_card': require('../assets/CharacterAssets/Ningguang/ningguang_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Ningguang/ningguang_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Ningguang/ningguang_face.png'),
    'c1': require('../assets/CharacterAssets/Ningguang/Ning_C1.png'),
    'c2': require('../assets/CharacterAssets/Ningguang/Ning_C2.png'),
    'c3': require('../assets/CharacterAssets/Ningguang/Ning_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Ningguang/Ning_C4.png'),
    'c5': require('../assets/CharacterAssets/Ningguang/Ning_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Ningguang/Ning_C6.png'),
  },
  "Noelle" :{
    'gacha_card': require('../assets/CharacterAssets/Noelle/noelle_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Noelle/noelle_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Noelle/noelle_face.png'),
    'c1': require('../assets/CharacterAssets/Noelle/Noelle_C1.png'),
    'c2': require('../assets/CharacterAssets/Noelle/Noelle_C2.png'),
    'c3': require('../assets/CharacterAssets/Noelle/Noelle_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Noelle/Noelle_C4.png'),
    'c5': require('../assets/CharacterAssets/Noelle/Noelle_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Noelle/Noelle_C6.png'),
  },
  "Qiqi" :{
    'gacha_card': require('../assets/CharacterAssets/Qiqi/qiqi_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Qiqi/qiqi_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Qiqi/qiqi_face.png'),
    'c1': require('../assets/CharacterAssets/Qiqi/Qiqi_C1.png'),
    'c2': require('../assets/CharacterAssets/Qiqi/Qiqi_C2.png'),
    'c3': require('../assets/CharacterAssets/Qiqi/Qiqi_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Qiqi/Qiqi_C4.png'),
    'c5': require('../assets/CharacterAssets/Qiqi/Qiqi_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Qiqi/Qiqi_C6.png'),
  },
  "Raiden Shogun" :{
    'gacha_card': require('../assets/CharacterAssets/Raiden Shogun/shougun_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Raiden Shogun/shougun_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Raiden Shogun/shougun_face.png'),
    'c1': require('../assets/CharacterAssets/Raiden Shogun/Raiden_C1.png'),
    'c2': require('../assets/CharacterAssets/Raiden Shogun/Raiden_C2.png'),
    'c3': require('../assets/CharacterAssets/Raiden Shogun/Raiden_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Raiden Shogun/Raiden_C4.png'),
    'c5': require('../assets/CharacterAssets/Raiden Shogun/Raiden_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Raiden Shogun/Raiden_C6.png'),
  },
  "Razor" :{
    'gacha_card': require('../assets/CharacterAssets/Razor/razor_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Razor/razor_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Razor/razor_face.png'),
    'c1': require('../assets/CharacterAssets/Razor/Razor_C1.png'),
    'c2': require('../assets/CharacterAssets/Razor/Razor_C2.png'),
    'c3': require('../assets/CharacterAssets/Razor/Razor_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Razor/Razor_C4.png'),
    'c5': require('../assets/CharacterAssets/Razor/Razor_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Razor/Razor_C6.png'),
  },
  "Rosaria" :{
    'gacha_card': require('../assets/CharacterAssets/Rosaria/rosaria_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Rosaria/rosaria_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Rosaria/rosaria_face.png'),
    'c1': require('../assets/CharacterAssets/Rosaria/Rosaria_C1.png'),
    'c2': require('../assets/CharacterAssets/Rosaria/Rosaria_C2.png'),
    'c3': require('../assets/CharacterAssets/Rosaria/Rosaria_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Rosaria/Rosaria_C4.png'),
    'c5': require('../assets/CharacterAssets/Rosaria/Rosaria_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Rosaria/Rosaria_C6.png'),
  },
  "Sangonomiya Kokomi" :{
    'gacha_card': require('../assets/CharacterAssets/Sangonomiya Kokomi/kokomi_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Sangonomiya Kokomi/kokomi_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Sangonomiya Kokomi/kokomi_face.png'),
    'c1': require('../assets/CharacterAssets/Sangonomiya Kokomi/Kokomi_C1.png'),
    'c2': require('../assets/CharacterAssets/Sangonomiya Kokomi/Kokomi_C2.png'),
    'c3': require('../assets/CharacterAssets/Sangonomiya Kokomi/Kokomi_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Sangonomiya Kokomi/Kokomi_C4.png'),
    'c5': require('../assets/CharacterAssets/Sangonomiya Kokomi/Kokomi_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Sangonomiya Kokomi/Kokomi_C6.png'),
  },
  "Sayu" :{
    'gacha_card': require('../assets/CharacterAssets/Sayu/sayu_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Sayu/sayu_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Sayu/sayu_face.png'),
    'c1': require('../assets/CharacterAssets/Sayu/Sayu_C1.png'),
    'c2': require('../assets/CharacterAssets/Sayu/Sayu_C2.png'),
    'c3': require('../assets/CharacterAssets/Sayu/Sayu_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Sayu/Sayu_C4.png'),
    'c5': require('../assets/CharacterAssets/Sayu/Sayu_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Sayu/Sayu_C6.png'),
  },
  "Shenhe" :{
    'gacha_card': require('../assets/CharacterAssets/Shenhe/shenhe_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Shenhe/shenhe_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Shenhe/shenhe_face.png'),
    'c1': require('../assets/CharacterAssets/Shenhe/Shenhe_C1.png'),
    'c2': require('../assets/CharacterAssets/Shenhe/Shenhe_C2.png'),
    'c3': require('../assets/CharacterAssets/Shenhe/Shenhe_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Shenhe/Shenhe_C4.png'),
    'c5': require('../assets/CharacterAssets/Shenhe/Shenhe_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Shenhe/Shenhe_C6.png'),
  },
  "Sucrose" :{
    'gacha_card': require('../assets/CharacterAssets/Sucrose/sucrose_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Sucrose/sucrose_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Sucrose/sucrose_face.png'),
    'c1': require('../assets/CharacterAssets/Sucrose/Sucrose_C1.png'),
    'c2': require('../assets/CharacterAssets/Sucrose/Sucrose_C2.png'),
    'c3': require('../assets/CharacterAssets/Sucrose/Sucrose_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Sucrose/Sucrose_C4.png'),
    'c5': require('../assets/CharacterAssets/Sucrose/Sucrose_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Sucrose/Sucrose_C6.png'),
  },
  "Tartaglia" :{
    'gacha_card': require('../assets/CharacterAssets/Tartaglia/tartaglia_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Tartaglia/tartaglia_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Tartaglia/tartaglia_face.png'),
    'c1': require('../assets/CharacterAssets/Tartaglia/Tartaglia_C1.png'),
    'c2': require('../assets/CharacterAssets/Tartaglia/Tartaglia_C2.png'),
    'c3': require('../assets/CharacterAssets/Tartaglia/Tartaglia_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Tartaglia/Tartaglia_C4.png'),
    'c5': require('../assets/CharacterAssets/Tartaglia/Tartaglia_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Tartaglia/Tartaglia_C6.png'),
  },
  "Thoma" :{
    'gacha_card': require('../assets/CharacterAssets/Thoma/thoma_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Thoma/thoma_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Thoma/thoma_face.png'),
    'c1': require('../assets/CharacterAssets/Thoma/Thoma_C1.png'),
    'c2': require('../assets/CharacterAssets/Thoma/Thoma_C2.png'),
    'c3': require('../assets/CharacterAssets/Thoma/Thoma_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Thoma/Thoma_C4.png'),
    'c5': require('../assets/CharacterAssets/Thoma/Thoma_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Thoma/Thoma_C6.png'),
  },
  "Venti" :{
    'gacha_card': require('../assets/CharacterAssets/Venti/venti_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Venti/venti_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Venti/venti_face.png'),
    'c1': require('../assets/CharacterAssets/Venti/Venti_C1.png'),
    'c2': require('../assets/CharacterAssets/Venti/Venti_C2.png'),
    'c3': require('../assets/CharacterAssets/Venti/Venti_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Venti/Venti_C4.png'),
    'c5': require('../assets/CharacterAssets/Venti/Venti_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Venti/Venti_C6.png'),
  },
  "Xiangling" :{
    'gacha_card': require('../assets/CharacterAssets/Xiangling/xiangling_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Xiangling/xiangling_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Xiangling/xiangling_face.png'),
    'c1': require('../assets/CharacterAssets/Xiangling/Xiangling_C1.png'),
    'c2': require('../assets/CharacterAssets/Xiangling/Xiangling_C2.png'),
    'c3': require('../assets/CharacterAssets/Xiangling/Xiangling_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Xiangling/Xiangling_C4.png'),
    'c5': require('../assets/CharacterAssets/Xiangling/Xiangling_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Xiangling/Xiangling_C6.png'),
  },
  "Xiao" :{
    'gacha_card': require('../assets/CharacterAssets/Xiao/xiao_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Xiao/xiao_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Xiao/xiao_face.png'),
    'c1': require('../assets/CharacterAssets/Xiao/Xiao_C1.png'),
    'c2': require('../assets/CharacterAssets/Xiao/Xiao_C2.png'),
    'c3': require('../assets/CharacterAssets/Xiao/Xiao_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Xiao/Xiao_C4.png'),
    'c5': require('../assets/CharacterAssets/Xiao/Xiao_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Xiao/Xiao_C6.png'),
  },
  "Xingqiu" :{
    'gacha_card': require('../assets/CharacterAssets/Xingqiu/xingqiu_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Xingqiu/xingqiu_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Xingqiu/xingqiu_face.png'),
    'c1': require('../assets/CharacterAssets/Xingqiu/Xingqiu_C1.png'),
    'c2': require('../assets/CharacterAssets/Xingqiu/Xingqiu_C2.png'),
    'c3': require('../assets/CharacterAssets/Xingqiu/Xingqiu_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Xingqiu/Xingqiu_C4.png'),
    'c5': require('../assets/CharacterAssets/Xingqiu/Xingqiu_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Xingqiu/Xingqiu_C6.png'),
  },
  "Xinyan" :{
    'gacha_card': require('../assets/CharacterAssets/Xinyan/xinyan_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Xinyan/xinyan_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Xinyan/xinyan_face.png'),
    'c1': require('../assets/CharacterAssets/Xinyan/Xinyan_C1.png'),
    'c2': require('../assets/CharacterAssets/Xinyan/Xinyan_C2.png'),
    'c3': require('../assets/CharacterAssets/Xinyan/Xinyan_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Xinyan/Xinyan_C4.png'),
    'c5': require('../assets/CharacterAssets/Xinyan/Xinyan_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Xinyan/Xinyan_C6.png'),
  },
  "Yae Miko" :{
    'gacha_card': require('../assets/CharacterAssets/Yae Miko/yaemiko_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Yae Miko/yaemiko_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Yae Miko/yaemiko_face.png'),
    'c1': require('../assets/CharacterAssets/Yae Miko/Yae_C1.png'),
    'c2': require('../assets/CharacterAssets/Yae Miko/Yae_C2.png'),
    'c3': require('../assets/CharacterAssets/Yae Miko/Yae_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Yae Miko/Yae_C4.png'),
    'c5': require('../assets/CharacterAssets/Yae Miko/Yae_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Yae Miko/Yae_C6.png'),
  },
  "Yanfei" :{
    'gacha_card': require('../assets/CharacterAssets/Yanfei/Yanfei_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Yanfei/Yanfei_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Yanfei/Yanfei_face.png'),
    'c1': require('../assets/CharacterAssets/Yanfei/Yanfei_C1.png'),
    'c2': require('../assets/CharacterAssets/Yanfei/Yanfei_C2.png'),
    'c3': require('../assets/CharacterAssets/Yanfei/Yanfei_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Yanfei/Yanfei_C4.png'),
    'c5': require('../assets/CharacterAssets/Yanfei/Yanfei_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Yanfei/Yanfei_C6.png'),
  },
  "Yelan" :{
    'gacha_card': require('../assets/CharacterAssets/Yelan/yelan_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Yelan/yelan_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Yelan/yelan_face.png'),
    'c1': require('../assets/CharacterAssets/Yelan/Yelan_C1.png'),
    'c2': require('../assets/CharacterAssets/Yelan/Yelan_C2.png'),
    'c3': require('../assets/CharacterAssets/Yelan/Yelan_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Yelan/Yelan_C4.png'),
    'c5': require('../assets/CharacterAssets/Yelan/Yelan_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Yelan/Yelan_C6.png'),
  },
  "Yoimiya" :{
    'gacha_card': require('../assets/CharacterAssets/Yoimiya/yoimiya_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Yoimiya/yoimiya_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Yoimiya/yoimiya_face.png'),
    'c1': require('../assets/CharacterAssets/Yoimiya/Yoimiya_C1.png'),
    'c2': require('../assets/CharacterAssets/Yoimiya/Yoimiya_C2.png'),
    'c3': require('../assets/CharacterAssets/Yoimiya/Yoimiya_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Yoimiya/Yoimiya_C4.png'),
    'c5': require('../assets/CharacterAssets/Yoimiya/Yoimiya_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Yoimiya/Yoimiya_C6.png'),
  },
  "Yun Jin" :{
    'gacha_card': require('../assets/CharacterAssets/Yun Jin/yunjin_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Yun Jin/yunjin_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Yun Jin/yunjin_face.png'),
    'c1': require('../assets/CharacterAssets/Yun Jin/Yunjin_C1.png'),
    'c2': require('../assets/CharacterAssets/Yun Jin/Yunjin_C2.png'),
    'c3': require('../assets/CharacterAssets/Yun Jin/Yunjin_C3_Burst.png'),
    'c4': require('../assets/CharacterAssets/Yun Jin/Yunjin_C4.png'),
    'c5': require('../assets/CharacterAssets/Yun Jin/Yunjin_C5_Skill.png'),
    'c6': require('../assets/CharacterAssets/Yun Jin/Yunjin_C6.png'),
  },
  "Zhongli" :{
    'gacha_card': require('../assets/CharacterAssets/Zhongli/zhongli_gacha_card.png'),
    'gacha_splash': require('../assets/CharacterAssets/Zhongli/zhongli_gacha_splash.png'),
    'icon': require('../assets/CharacterAssets/Zhongli/zhongli_face.png'),
    'c1': require('../assets/CharacterAssets/Zhongli/Zhongli_C1.png'),
    'c2': require('../assets/CharacterAssets/Zhongli/Zhongli_C2.png'),
    'c3': require('../assets/CharacterAssets/Zhongli/Zhongli_C3_Skill.png'),
    'c4': require('../assets/CharacterAssets/Zhongli/Zhongli_C4.png'),
    'c5': require('../assets/CharacterAssets/Zhongli/Zhongli_C5_Burst.png'),
    'c6': require('../assets/CharacterAssets/Zhongli/Zhongli_C6.png'),
  },
}

export default characterAssets;